version: '3'

services:
  employee-svc:
    image: thej1/employee-svc:0.0.2
    ports:
      - 7101:7101
    networks:
      - testlocal
  employee-svc-dapr:
    image: "daprio/daprd:edge"
    command: [ "./daprd",
               "-app-id", "employee-svc",
               "-app-port", "7101",
               "-app-protocol","http",
               "-dapr-http-port", "3501",
               "-dapr-grpc-port", "50001",
               "-log-level", "debug",
               "-components-path", "/components" ]
    volumes:
      - "./components/:/components"
    depends_on:
      - employee-svc
    network_mode: "service:employee-svc"

  employee-data-svc:
    image: thej1/employee-data-svc:latest
    ports:
      - 7100:7100
    networks:
      - testlocal

  employee-data-svc-dapr:
    image: "daprio/daprd:edge"
    command: [ "./daprd",
               "-app-id", "employee-data-svc",
               "-app-port", "7100",
               "-app-protocol","http",
               "-dapr-http-port", "3500",
               "-dapr-grpc-port", "50000",
               "-log-level", "debug",
               "-components-path", "/components" ]
    volumes:
      - "./components/:/components"  bv
    depends_on:
      - employee-data-svc
    network_mode: "service:employee-data-svc"

networks:
  testlocal:
    driver: bridge

